import = ["~/.cache/wallust/colors-alacritty.toml"]

[window]
dinamic_padding = true

[font]
normal = { family = "JetBrainsMono Nerdfont", style = "Regular"}
size = 14.0
# offset = { x = 12, y = 12 }
